101-fix-gender-dropdown-style-and-make-it-selectable
softwarebyze/Places pull request #103
Opened 2023-07-27 18:49 UTC by simonac2-gif

This is the right pull request. For 101 not 59

2023-07-27 21:57 UTC, softwarebyze requested changes

2023-07-27 21:57 UTC, softwarebyze commented on components/Start/elements/Details.js
> +import RadioForm from "react-native-simple-radio-button";
This library isn't in our package.json and theres no changes to our package json in this PR so I'm getting an error that it's not found. We should be able to implement this ourselves without pulling in a library

2023-07-27 21:57 UTC, softwarebyze commented on components/Start/elements/Details.js
> +  TouchableNativeFeedback,
not sure why [TouchableNativeFeedback](https://reactnative.dev/docs/touchablenativefeedback) is being imported

2023-08-01 02:09 UTC, softwarebyze approved these changes

2023-08-01 02:13 UTC, softwarebyze commented
https://github.com/softwarebyze/Places/assets/77241170/d9714fc4-ce84-4784-b9d1-cbb2cfbd03f8

2023-08-01 02:14 UTC, softwarebyze commented
https://github.com/softwarebyze/Places/assets/77241170/3d8f64fd-7185-4df1-a72e-a8c4313fd8ba

2023-08-01 04:00 UTC, softwarebyze approved these changes

2023-08-01 04:01 UTC, softwarebyze commented
https://github.com/softwarebyze/Places/assets/77241170/1eddd642-8252-4c30-87bc-fb1f1a1d6e8b

2023-08-01 04:01 UTC, simonac2-gif commented
IOS and Android differences with code

2023-08-01 04:02 UTC, merged