90-query-for-cities
softwarebyze/Places pull request #197
Opened 2023-08-27 15:08 UTC by Avraham-S

moved functions to designated folder

2023-08-28 23:07 UTC, softwarebyze requested changes

2023-08-28 23:07 UTC, softwarebyze commented on firebase/users.js
> +const fetchUsersCities = async (setStateFunction) => {
Any reason why we can't just return the cities?

2023-08-28 23:07 UTC, softwarebyze commented on firebase/users.js
> +          id: Date.now() + i + Math.random(),
Why do we need to add an id here?

2023-08-29 18:45 UTC, Avraham-S commented on firebase/users.js
> +const fetchUsersCities = async (setStateFunction) => {
We could do that. I'll change it

2023-08-29 18:46 UTC, Avraham-S commented on firebase/users.js
> +          id: Date.now() + i + Math.random(),
It was for the react key, but I'll remove it and just use the city name

2023-09-05 16:52 UTC, softwarebyze requested changes
After these changes, can you please add a demo screen recording

2023-09-05 16:52 UTC, softwarebyze commented on components/pages/HomePage.js
> +    fetchUsersCities().then((cities) => setCities(cities));
i prefer async await syntax here (and creating a function inside the useEffect)

2023-09-05 16:52 UTC, softwarebyze commented on firebase/users.js
> +const addUserCity = async (city, usersCities) => {
id rather just take the one city to add here and fetch the current cities within the function

2023-09-05 19:57 UTC, Avraham-S commented
https://github.com/softwarebyze/Places/assets/103695563/45036b31-3ec4-4d1f-b2e7-16a29388e12b

No new functionality, just refactoring

2023-09-06 00:27 UTC, softwarebyze approved these changes

2023-09-06 00:27 UTC, merged